name: Release
on:
  push:
    branches: [ master ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      issues: write 
      pull-requests: write 
      id-token: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'npm'
      - name: Install dependencies
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          npm ci --ignore-scripts
          npm run prepare --if-present
      - name: Verify the integrity of provenance attestations and registry signatures
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release